/**
 * vr.js library main code.
 *
 * @author Ben Vanik <ben.vanik@gmail.com>
 * @license Apache 2.0
 * @module vr
 */
/*
  This version was generated using "Simple" optimization on
  http://closure-compiler.appspot.com/home applied to vr.js version
  3822724bf0e6b01c04971933ff5d4d1cfba7729b
*/
(function(f){function B(a,d){function c(){}c.prototype=d.prototype;a.superClass_=d.prototype;a.prototype=new c;a.prototype.constructor=a}var b={ErrorCode:{PLUGIN_NOT_FOUND:1,PLUGIN_BLOCKED:4},DataSourceMode:{PLUGIN:0,DRIVER:1},DataSource:function(){}};b.DataSource.prototype.dispose=function(){};b.DataSource.prototype.isPresent=function(){return!1};b.DataSource.prototype.load=function(a,d){f.setTimeout(function(){a.call(d,null)},0)};b.DataSource.prototype.queryHmdInfo=function(){return null};b.DataSource.prototype.querySixenseInfo=
function(){return null};b.DataSource.prototype.resetHmdOrientation=function(){};b.DataSource.prototype.poll=function(a){};b.PluginDataSource=function(a){b.DataSource.call(this);this.document_=a;this.native_=null};B(b.PluginDataSource,b.DataSource);b.PluginDataSource.prototype.dispose=function(){b.DataSource.prototype.dispose.call(this)};b.PluginDataSource.prototype.isPresent=function(){var a=navigator.plugins;a.refresh();for(var d=0;d<a.length;d++)for(var c=a[d],b=0;b<c.length;b++)if("application/x-vnd-vr"==
c[b].type)return!0;return!1};b.PluginDataSource.prototype.createEmbed_=function(){var a=this.document_.createElement("embed");a.type="application/x-vnd-vr";a.width=4;a.height=4;a.style.visibility="hidden";a.style.width="0";a.style.height="0";a.style.margin="0";a.style.padding="0";a.style.borderStyle="none";a.style.borderWidth="0";a.style.maxWidth="0";a.style.maxHeight="0";return a};b.PluginDataSource.prototype.load=function(a,d){function c(){if(f._vr_native_)h.native_=f._vr_native_,a.call(d,null);
else if(5E3<Date.now()-k){h.native_=null;var e=Error("Plugin blocked - enable and reload.");e.code=b.ErrorCode.PLUGIN_BLOCKED;a.call(d,e)}else f.setTimeout(c,100)}var e=this.createEmbed_();this.document_.body.appendChild(e);var k=Date.now(),h=this;c()};b.PluginDataSource.prototype.execCommand_=function(a,d){return this.native_?this.native_.exec(a,d||"")||"":""};b.PluginDataSource.prototype.queryHmdInfo=function(){var a=this.execCommand_(1);if(!a||!a.length)return null;a=a.split(",");return new b.HmdInfo(a)};
b.PluginDataSource.prototype.querySixenseInfo=function(){return new b.SixenseInfo};b.PluginDataSource.prototype.resetHmdOrientation=function(){this.execCommand_(2)};b.PluginDataSource.prototype.poll=function(a){if(this.native_)for(var d=this.native_.poll().split("|"),c=0;c<d.length;c++){var b=d[c].split(",");if(b.length)switch(b[0]){case "s":this.parseSixenseChunk_(a,b,1);break;case "r":this.parseHmdChunk_(a,b,1)}}};b.PluginDataSource.prototype.parseSixenseChunk_=function(a,d,c){for(;c<d.length;){var b=
d[c++];if("b"==b)c++,a.sixense.present=!0;else if("c"==b)b=d[c++],b=a.sixense.controllers[b],b.position[0]=parseFloat(d[c++]),b.position[1]=parseFloat(d[c++]),b.position[2]=parseFloat(d[c++]),b.rotation[0]=parseFloat(d[c++]),b.rotation[1]=parseFloat(d[c++]),b.rotation[2]=parseFloat(d[c++]),b.rotation[3]=parseFloat(d[c++]),b.joystick[0]=parseFloat(d[c++]),b.joystick[1]=parseFloat(d[c++]),b.trigger=parseFloat(d[c++]),b.buttons=parseInt(d[c++],10),b.isDocked="1"==d[c++],b.hand=parseInt(d[c++],10),b.isTrackingHemispheres=
"1"==d[c++];else break}};b.PluginDataSource.prototype.parseHmdChunk_=function(a,d,b){5==d.length?(a.hmd.present=!0,a.hmd.rotation[0]=parseFloat(d[b++]),a.hmd.rotation[1]=parseFloat(d[b++]),a.hmd.rotation[2]=parseFloat(d[b++]),a.hmd.rotation[3]=parseFloat(d[b++])):a.hmd.present=!1};b.DriverDataSource=function(a){b.DataSource.call(this);this.driver_=a};B(b.DriverDataSource,b.DataSource);b.DriverDataSource.prototype.dispose=function(){this.driver_.dispose();b.DataSource.prototype.dispose.call(this)};
b.DriverDataSource.prototype.isPresent=function(){return!0};b.DriverDataSource.prototype.load=function(a,d){f.setTimeout(function(){a.call(d,null)},0)};b.DriverDataSource.prototype.queryHmdInfo=function(){var a=new b.HmdInfo;return this.driver_.fillHmdInfo(a)?a:null};b.DriverDataSource.prototype.querySixenseInfo=function(){return null};b.DriverDataSource.prototype.resetHmdOrientation=function(){this.driver_.resetOrientation()};b.DriverDataSource.prototype.poll=function(a){var d=this.driver_.isPresent();
(a.hmd.present=d)?this.driver_.getOrientation(a.hmd.rotation):(a.hmd.rotation[0]=a.hmd.rotation[1]=a.hmd.rotation[2]=0,a.hmd.rotation[3]=0)};b.Runtime=function(a){this.document_=a;this.dataSourceMode_=b.DataSourceMode.PLUGIN;f.__vr_driver__&&(this.dataSourceMode_=b.DataSourceMode.DRIVER);var d=null;switch(this.dataSourceMode_){default:case b.DataSourceMode.PLUGIN:d=new b.PluginDataSource(this.document_);break;case b.DataSourceMode.DRIVER:d=new b.DriverDataSource(f.__vr_driver__)}this.dataSource_=
d;this.isInstalled_=this.dataSource_.isPresent();this.isLoaded_=!1;this.error_=null;this.isLoading_=!1;this.readyWaiters_=[];this.oldWindowSize_=this.sixenseInfo_=this.hmdInfo_=null;var c=this,d=function(a){c.fullScreenChange_(a)};a.addEventListener("fullscreenchange",d,!1);a.addEventListener("mozfullscreenchange",d,!1)};b.Runtime.prototype.load=function(a,d){var c=this;if(this.isInstalled_)this.isLoaded_||this.error?a&&f.setTimeout(function(){a.call(d,c.error_)},0):(a&&this.readyWaiters_.push([a,
d]),this.isLoading_||(this.isLoading_=!0,b.waitForDomReady(this.document_,function(){this.dataSource_.load(function(a){this.completeLoad_(a)},this)},this)));else{var e=Error("Plugin not installed!");e.code=b.ErrorCode.PLUGIN_NOT_FOUND;this.error_=e;a&&f.setTimeout(function(){a.call(d,c.error_)},0)}};b.Runtime.prototype.completeLoad_=function(a){a?(this.isLoaded_=!1,this.error_=a):(this.isLoaded_=!0,this.error_=null);for(;this.readyWaiters_.length;){var d=this.readyWaiters_.shift();d[0].call(d[1],
a||null)}};b.Runtime.prototype.poll=function(a){a.sixense.present=!1;a.hmd.present=!1;this.dataSource_.poll(a);a.sixense.present&&!this.sixenseInfo_?this.sixenseInfo_=this.dataSource_.querySixenseInfo():!a.sixense.present&&this.sixenseInfo_&&(this.sixenseInfo_=null);a.hmd.present&&!this.hmdInfo_?this.hmdInfo_=this.dataSource_.queryHmdInfo():!a.hmd.present&&this.hmdInfo_&&(this.hmdInfo_=null);return!0};b.Runtime.prototype.fullScreenChange_=function(a){!b.isFullScreen()&&this.oldWindowSize_&&(f.moveTo(this.oldWindowSize_[0],
this.oldWindowSize_[1]),f.resizeTo(this.oldWindowSize_[2],this.oldWindowSize_[3]),this.oldWindowSize_=null)};b.runtime_=new b.Runtime(f.document);b.isInstalled=function(){return b.runtime_.isInstalled_};b.isLoaded=function(){return b.runtime_.isLoaded_};b.getError=function(){return b.runtime_.error_};b.load=function(a,d){b.runtime_.load(a,d)};b.getHmdInfo=function(){return b.runtime_.hmdInfo_};b.resetHmdOrientation=function(){b.runtime_.dataSource_.resetHmdOrientation()};b.getSixenseInfo=function(){return b.runtime_.sixenseInfo_};
b.pollState=function(a){return b.runtime_.poll(a)};b.isFullScreen=function(){var a=b.runtime_;return!!(a.document_.fullScreenElement||a.document_.mozFullScreenElement||a.document_.webkitFullscreenElement)};b.enterFullScreen=function(){var a=b.runtime_;a.oldWindowSize_=[f.screenX,f.screenY,f.outerWidth,f.outerHeight];var d=a.hmdInfo_;d&&(f.moveTo(d.desktopX,d.desktopY),f.resizeTo(d.resolutionHorz,d.resolutionVert));(a.document_.documentElement.requestFullscreen||a.document_.documentElement.mozRequestFullScreen||
a.document_.documentElement.webkitRequestFullScreen).call(a.document_.documentElement,Element.ALLOW_KEYBOARD_INPUT);return!0};b.exitFullScreen=function(){var a=b.runtime_,d=a.document_.cancelFullScreen||a.document_.mozCancelFullScreen||a.document_.webkitCancelFullScreen;d&&d.call(a.document_)};b.requestAnimationFrame=function(a,d){var b=f.requestAnimationFrame||f.mozRequestAnimationFrame||f.msRequestAnimationFrame||f.oRequestAnimationFrame||f.webkitRequestAnimationFrame;return d?b.call(f,function(){return a.apply(d,
arguments)}):b.call(f,a)};b.waitForDomReady=function(a,b,c){if("interactive"==a.readyState||"complete"==a.readyState)f.setTimeout(function(){b.call(c)},0);else{var e=function(){a.removeEventListener("DOMContentLoaded",e,!1);b.call(c)};a.addEventListener("DOMContentLoaded",e,!1)}};b.log=function(a){f.console&&f.console.log&&f.console.log.apply(f.console,arguments)};b.HmdInfo=function(a){var b=0;this.deviceName=a?a[b++]:"Mock Device";this.deviceManufacturer=a?a[b++]:"vr.js";this.deviceVersion=a?parseFloat(a[b++]):
0;this.desktopX=a?parseFloat(a[b++]):0;this.desktopY=a?parseFloat(a[b++]):0;this.resolutionHorz=a?parseFloat(a[b++]):1280;this.resolutionVert=a?parseFloat(a[b++]):800;this.screenSizeHorz=a?parseFloat(a[b++]):.14976;this.screenSizeVert=a?parseFloat(a[b++]):.0936;this.screenCenterVert=a?parseFloat(a[b++]):400;this.eyeToScreenDistance=a?parseFloat(a[b++]):.041;this.lensSeparationDistance=a?parseFloat(a[b++]):.0635;this.interpupillaryDistance=a?parseFloat(a[b++]):.0635;this.distortionK=new Float32Array(a?
[parseFloat(a[b++]),parseFloat(a[b++]),parseFloat(a[b++]),parseFloat(a[b++])]:[1,.22,.24,0]);this.chromaAbCorrection=new Float32Array(a?[parseFloat(a[b++]),parseFloat(a[b++]),parseFloat(a[b++]),parseFloat(a[b++])]:[1,0,1,0])};b.HmdInfo.prototype.toString=function(){return this.deviceName+" v"+this.deviceVersion+" ("+this.deviceManufacturer+")"};b.HmdInfo.prototype.distort=function(a){var b=a*a,c=this.distortionK;return a*(c[0]+c[1]*b+c[2]*b*b+c[3]*b*b*b)};b.HmdInfo.DEFAULT=new b.HmdInfo;b.HmdState=
function(){this.present=!1;this.rotation=new Float32Array(4)};b.SixenseButton={NONE:0,BUTTON_START:1,BUTTON_1:32,BUTTON_2:64,BUTTON_3:8,BUTTON_4:16,BUMPER:128,JOYSTICK:256};b.SixenseHand={UNKNOWN:0,LEFT:1,RIGHT:2};b.SixenseInfo=function(a){};b.SixenseState=function(){this.present=!1;this.controllers=[new b.SixenseControllerState,new b.SixenseControllerState]};b.SixenseControllerState=function(){this.position=new Float32Array(3);this.rotation=new Float32Array(4);this.joystick=new Float32Array(2);this.trigger=
0;this.buttons=b.SixenseButton.NONE;this.isDocked=!1;this.hand=b.SixenseHand.UNKNOWN;this.isTrackingHemispheres=!1};b.State=function(){this.sixense=new b.SixenseState;this.hmd=new b.HmdState};b.mat4f={};b.mat4f.create=function(){return new Float32Array(16)};b.mat4f.makeIdentity=function(a){a[0]=a[5]=a[10]=a[15]=1;a[1]=a[2]=a[3]=a[4]=a[6]=a[7]=a[8]=a[9]=a[11]=a[12]=a[13]=a[14]=0};b.mat4f.makeTranslation=function(a,b,c,e){a[0]=a[5]=a[10]=a[15]=1;a[1]=a[2]=a[3]=a[4]=a[6]=a[7]=a[8]=a[9]=a[11]=0;a[12]=
b;a[13]=c;a[14]=e};b.mat4f.makeRect=function(a,b,c,e,k){a[0]=e;a[5]=k;a[10]=a[15]=1;a[1]=a[2]=a[3]=a[4]=a[6]=a[7]=a[8]=a[9]=a[11]=a[14]=0;a[12]=b;a[13]=c};b.mat4f.makePerspective=function(a,b,c,e,k){b=1/Math.tan(b/2);var h=1/(e-k);a[0]=b/c;a[1]=a[2]=a[3]=a[4]=0;a[5]=b;a[6]=a[7]=a[8]=a[9]=0;a[10]=(k+e)*h;a[11]=-1;a[12]=a[13]=0;a[14]=2*k*e*h;a[15]=0};b.mat4f.multiply=function(a,b,c){var e=b[0],k=b[1],h=b[2],g=b[3],f=b[4],q=b[5],s=b[6],t=b[7],u=b[8],v=b[9],w=b[10],x=b[11],y=b[12],z=b[13],A=b[14];b=b[15];
var l,m,n,p;l=c[0];m=c[1];n=c[2];p=c[3];a[0]=l*e+m*f+n*u+p*y;a[1]=l*k+m*q+n*v+p*z;a[2]=l*h+m*s+n*w+p*A;a[3]=l*g+m*t+n*x+p*b;l=c[4];m=c[5];n=c[6];p=c[7];a[4]=l*e+m*f+n*u+p*y;a[5]=l*k+m*q+n*v+p*z;a[6]=l*h+m*s+n*w+p*A;a[7]=l*g+m*t+n*x+p*b;l=c[8];m=c[9];n=c[10];p=c[11];a[8]=l*e+m*f+n*u+p*y;a[9]=l*k+m*q+n*v+p*z;a[10]=l*h+m*s+n*w+p*A;a[11]=l*g+m*t+n*x+p*b;l=c[12];m=c[13];n=c[14];p=c[15];a[12]=l*e+m*f+n*u+p*y;a[13]=l*k+m*q+n*v+p*z;a[14]=l*h+m*s+n*w+p*A;a[15]=l*g+m*t+n*x+p*b};b.Program=function(a,b,c,e,k,
h){this.gl_=a;this.attributes={};for(var g=0;g<k.length;g++)this.attributes[k[g]]=-1;this.uniforms={};for(g=0;g<h.length;g++)this.uniforms[h[g]]=null;this.program_=a.createProgram();this.program_.displayName=b;k=a.createShader(a.VERTEX_SHADER);k.displayName=b+":VS";a.shaderSource(k,c);a.attachShader(this.program_,k);c=a.createShader(a.FRAGMENT_SHADER);c.displayName=b+":FS";a.shaderSource(c,e);a.attachShader(this.program_,c)};b.Program.prototype.dispose=function(){this.gl_.deleteProgram(this.program_)};
b.Program.prototype.beginLinking=function(){for(var a=this.gl_,b=a.getAttachedShaders(this.program_),c=0;c<b.length;c++)a.compileShader(b[c]);a.linkProgram(this.program_)};b.Program.prototype.endLinking=function(){for(var a=this.gl_,d=a.getAttachedShaders(this.program_),c=0;c<d.length;c++){var e=d[c].displayName,k=a.getShaderInfoLog(d[c]);if(a.getShaderParameter(d[c],a.COMPILE_STATUS))k&&k.length&&b.log("Shader "+e+" compilation warnings:\n"+k);else throw"Shader "+e+" compilation errors:\n"+k;}d=
this.program_.displayName;c=a.getProgramInfoLog(this.program_);if(a.getProgramParameter(this.program_,a.LINK_STATUS))c&&c.length&&b.log("Program "+d+" link warnings:\n"+c);else throw"Program "+d+" link errors:\n"+c;for(var h in this.attributes)this.attributes[h]=a.getAttribLocation(this.program_,h);for(var g in this.uniforms)this.uniforms[g]=a.getUniformLocation(this.program_,g)};b.Program.prototype.use=function(){this.gl_.useProgram(this.program_)};b.StereoEye=function(a,b,c,e){this.viewport=[a,
b,c,e];this.distortionCenterOffsetY=this.distortionCenterOffsetX=0;this.projectionMatrix=new Float32Array(16);this.viewAdjustMatrix=new Float32Array(16);this.orthoProjectionMatrix=new Float32Array(16)};b.StereoParams=function(){this.zNear_=.01;this.zFar_=1E3;this.interpupillaryDistance_=void 0;this.distortionScale_=1;this.distortionFitX_=-1;this.distortionFitY_=0;this.eyes_=[new b.StereoEye(0,0,.5,1),new b.StereoEye(.5,0,.5,1)];this.tmpMat4s_=[b.mat4f.create(),b.mat4f.create()]};b.StereoParams.prototype.setZNear=
function(a){this.zNear_=a};b.StereoParams.prototype.setZFar=function(a){this.zFar_=a};b.StereoParams.prototype.getInterpupillaryDistance=function(){return this.interpupillaryDistance_};b.StereoParams.prototype.setInterpupillaryDistance=function(a){this.interpupillaryDistance_=a};b.StereoParams.prototype.getDistortionScale=function(){return this.distortionScale_};b.StereoParams.prototype.getEyes=function(){return[this.eyes_[0],this.eyes_[1]]};b.StereoParams.prototype.update=function(a){var d=a.interpupillaryDistance;
void 0!==this.interpupillaryDistance_&&(d=this.interpupillaryDistance_);var c=4*(a.screenSizeHorz/4-a.lensSeparationDistance/2)/a.screenSizeHorz;if(1E-4>Math.abs(this.distortionFitX_)&&1E-4>Math.abs(this.distortionFitY_))this.distortionScale_=1;else{var e=this.distortionFitX_-c,k=this.distortionFitY_/(a.resolutionHorz/a.resolutionVert/2),e=Math.sqrt(e*e+k*k);this.distortionScale_=a.distort(e)/e}var e=2*Math.atan(a.screenSizeVert/2*this.distortionScale_/a.eyeToScreenDistance),k=4*(a.screenSizeHorz/
4-a.lensSeparationDistance/2)/a.screenSizeHorz,h=a.resolutionHorz/a.screenSizeHorz,g=h*a.lensSeparationDistance,h=a.eyeToScreenDistance/.8*h*d,f=a.resolutionHorz/2-g/2-g/2,g=2*Math.tan(85*Math.PI/180/2)*a.eyeToScreenDistance/this.distortionScale_,g=a.resolutionVert*g/a.screenSizeVert,h=(f+h/this.distortionScale_)/2,h=2*h/g,f=this.eyes_[0],q=this.eyes_[1];f.distortionCenterOffsetX=c;f.distortionCenterOffsetY=0;q.distortionCenterOffsetX=-c;q.distortionCenterOffsetY=0;b.mat4f.makeIdentity(f.viewAdjustMatrix);
f.viewAdjustMatrix[12]=-d/2;b.mat4f.makeIdentity(q.viewAdjustMatrix);q.viewAdjustMatrix[12]=d/2;d=this.tmpMat4s_[0];c=this.tmpMat4s_[1];b.mat4f.makePerspective(d,e,a.resolutionHorz/a.resolutionVert/2,this.zNear_,this.zFar_);b.mat4f.makeTranslation(c,k,0,0);b.mat4f.multiply(f.projectionMatrix,c,d);b.mat4f.makeTranslation(c,-k,0,0);b.mat4f.multiply(q.projectionMatrix,c,d);d=this.tmpMat4s_[0];c=this.tmpMat4s_[1];b.mat4f.makeIdentity(d);d[0]=g/(a.resolutionHorz/2);d[5]=-g/a.resolutionVert;b.mat4f.makeTranslation(c,
h,0,0);b.mat4f.multiply(f.orthoProjectionMatrix,d,c);b.mat4f.makeTranslation(c,-h,0,0);b.mat4f.multiply(q.orthoProjectionMatrix,d,c)};b.PostProcessingMode={STRAIGHT:0,WARP:1,WARP_CHROMEAB:2};b.StereoRenderer=function(a,d){this.gl_=a;this.attributes_=d||{};this.hmdPresent_=this.isInitialized_=!1;this.hmdInfo_=new b.HmdInfo;this.quadBuffer_=a.createBuffer();this.quadBuffer_.displayName="vr.StereoRendererQuad";var c=a.getParameter(a.ARRAY_BUFFER_BINDING);a.bindBuffer(a.ARRAY_BUFFER,this.quadBuffer_);
a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0,0,0,1,0,1,0,0,1,0,1,1,0,1,0,1,1,1,1,0,1,0,1]),a.STATIC_DRAW);a.bindBuffer(a.ARRAY_BUFFER,c);this.straightProgram_=new b.Program(a,"vr.StereoRendererStraight",b.StereoRenderer.PROGRAM_VERTEX_SOURCE_,b.StereoRenderer.STRAIGHT_FRAGMENT_SOURCE_,b.StereoRenderer.PROGRAM_ATTRIBUTE_NAMES_,b.StereoRenderer.PROGRAM_UNIFORM_NAMES_);this.warpProgram_=new b.Program(a,"vr.StereoRendererWarp",b.StereoRenderer.PROGRAM_VERTEX_SOURCE_,b.StereoRenderer.WARP_FRAGMENT_SOURCE_,
b.StereoRenderer.PROGRAM_ATTRIBUTE_NAMES_,b.StereoRenderer.PROGRAM_UNIFORM_NAMES_);this.warpChromeAbProgram_=new b.Program(a,"vr.StereoRendererWarpChromeAb",b.StereoRenderer.PROGRAM_VERTEX_SOURCE_,b.StereoRenderer.WARP_CHROMEAB_FRAGMENT_SOURCE_,b.StereoRenderer.PROGRAM_ATTRIBUTE_NAMES_,b.StereoRenderer.PROGRAM_UNIFORM_NAMES_);this.postProcessingMode_=b.PostProcessingMode.WARP_CHROMEAB;this.postProcessingProgram_=this.warpChromeAbProgram_;this.updateAllUniforms_=!0;this.framebuffer_=a.createFramebuffer();
this.framebuffer_.displayName="vr.StereoRendererFB";this.framebufferAttachments_=[];this.renderTargetHeight_=this.renderTargetWidth_=0;this.renderTexture_=a.createTexture();this.renderTexture_.displayName="vr.StereoRendererRT";this.stereoParams_=new b.StereoParams;this.tmpMat4_=b.mat4f.create();for(var c=[this.straightProgram_,this.warpProgram_,this.warpChromeAbProgram_],e=0;e<c.length;e++)c[e].beginLinking();for(e=0;e<c.length;e++)c[e].endLinking();this.initialize_()};b.StereoRenderer.RENDER_TARGET_SCALE_=
2;b.StereoRenderer.prototype.dispose=function(){for(var a=this.gl_,b=0;b<this.framebufferAttachments_.length;b++)a.deleteRenderbuffer(this.framebufferAttachments_[b]);a.deleteTexture(this.renderTexture_);a.deleteFramebuffer(this.framebuffer_);a.deleteBuffer(this.quadBuffer_);this.straightProgram_&&this.straightProgram_.dispose();this.warpProgram_&&this.warpProgram_.dispose();this.warpChromeAbProgram_&&this.warpChromeAbProgram_.dispose()};b.StereoRenderer.prototype.getParams=function(){return this.stereoParams_};
b.StereoRenderer.prototype.getPostProcessingMode=function(){return this.postProcessingMode_};b.StereoRenderer.prototype.setPostProcessingMode=function(a){if(a!=this.postProcessingMode_)switch(this.updateAllUniforms_=!0,this.postProcessingMode_=a,a){case b.PostProcessingMode.STRAIGHT:this.postProcessingProgram_=this.straightProgram_;break;case b.PostProcessingMode.WARP:this.postProcessingProgram_=this.warpProgram_;break;default:case b.PostProcessingMode.WARP_CHROMEAB:this.postProcessingProgram_=this.warpChromeAbProgram_}};
b.StereoRenderer.prototype.initialize_=function(){var a=this.gl_,d=this.hmdInfo_;a.canvas.width!=d.resolutionHorz&&(a.canvas.width=d.resolutionHorz,a.canvas.height=d.resolutionVert,a.canvas.style.width=a.canvas.width+"px",a.canvas.style.height=a.canvas.height+"px");this.setupRenderTarget_(d.resolutionHorz*b.StereoRenderer.RENDER_TARGET_SCALE_,d.resolutionVert*b.StereoRenderer.RENDER_TARGET_SCALE_);this.isInitialized_=this.updateAllUniforms_=!0};b.StereoRenderer.prototype.setupRenderTarget_=function(a,
b){var c=this.gl_;a=Math.floor(a)||4;b=Math.floor(b)||4;if(this.renderTargetWidth_!=a||this.renderTargetHeight_!=b){this.renderTargetWidth_=a;this.renderTargetHeight_=b;var e=c.getParameter(c.FRAMEBUFFER_BINDING),f=c.getParameter(c.RENDERBUFFER_BINDING),h=c.getParameter(c.TEXTURE_BINDING_2D);c.bindFramebuffer(c.FRAMEBUFFER,this.framebuffer_);c.bindTexture(c.TEXTURE_2D,this.renderTexture_);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,
c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_S,c.CLAMP_TO_EDGE);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_T,c.CLAMP_TO_EDGE);c.texImage2D(c.TEXTURE_2D,0,this.attributes_.alpha?c.RGBA:c.RGB,a,b,0,this.attributes_.alpha?c.RGBA:c.RGB,c.UNSIGNED_BYTE,null);c.framebufferTexture2D(c.FRAMEBUFFER,c.COLOR_ATTACHMENT0,c.TEXTURE_2D,this.renderTexture_,0);for(var g=0;g<this.framebufferAttachments_.length;g++)c.deleteRenderbuffer(this.framebufferAttachments_[g]);this.framebufferAttachments_=[];g=null;
this.attributes_.depth&&(g=c.createRenderbuffer(),c.bindRenderbuffer(c.RENDERBUFFER,g),c.renderbufferStorage(c.RENDERBUFFER,c.DEPTH_COMPONENT16,a,b),this.framebufferAttachments_.push(g));c.framebufferRenderbuffer(c.FRAMEBUFFER,c.DEPTH_ATTACHMENT,c.RENDERBUFFER,g);g=null;this.attributes_.stencil&&(g=c.createRenderbuffer(),c.bindRenderbuffer(c.RENDERBUFFER,g),c.renderbufferStorage(c.RENDERBUFFER,c.STENCIL_INDEX8,a,b),this.framebufferAttachments_.push(g));c.framebufferRenderbuffer(c.FRAMEBUFFER,c.STENCIL_ATTACHMENT,
c.RENDERBUFFER,g);g=c.FRAMEBUFFER_COMPLETE;g=c.checkFramebufferStatus(c.FRAMEBUFFER);c.bindFramebuffer(c.FRAMEBUFFER,e);c.bindRenderbuffer(c.RENDERBUFFER,f);c.bindTexture(c.TEXTURE_2D,h);if(g!=c.FRAMEBUFFER_COMPLETE)throw"Invalid framebuffer: "+g;}};b.StereoRenderer.prototype.getInterpupillaryDistance=function(){var a=this.hmdInfo_,b=this.stereoParams_.getInterpupillaryDistance();return void 0!==b?b:a.interpupillaryDistance};b.StereoRenderer.prototype.setInterpupillaryDistance=function(a){this.stereoParams_.setInterpupillaryDistance(a)};
b.StereoRenderer.prototype.render=function(a,d,c){var e=this.gl_;a=a.hmd.present;a!=this.hmdPresent_&&(this.hmdPresent_=!0,this.hmdInfo_=a?b.getHmdInfo():new b.HmdInfo,this.initialize_());this.stereoParams_.update(this.hmdInfo_);if(this.isInitialized_){a=this.stereoParams_.getEyes();for(var f=0;f<a.length;f++){var h=a[f];e.bindFramebuffer(e.FRAMEBUFFER,this.framebuffer_);e.viewport(h.viewport[0]*this.renderTargetWidth_,h.viewport[1]*this.renderTargetHeight_,h.viewport[2]*this.renderTargetWidth_,h.viewport[3]*
this.renderTargetHeight_);d.call(c,h,this.renderTargetWidth_,this.renderTargetHeight_);e.bindFramebuffer(e.FRAMEBUFFER,null);this.renderEye_(h)}e.flush()}};b.StereoRenderer.prototype.renderEye_=function(a){var d=this.gl_;d.activeTexture(d.TEXTURE0);d.bindTexture(d.TEXTURE_2D,this.renderTexture_);var c=this.postProcessingProgram_;c.use();this.updateAllUniforms_&&(this.updateAllUniforms_=!1,d.uniform1i(c.uniforms.u_tex0,0),d.uniform4fv(c.uniforms.u_hmdWarpParam,this.hmdInfo_.distortionK),d.uniform4fv(c.uniforms.u_chromAbParam,
this.hmdInfo_.chromaAbCorrection));var e=this.hmdInfo_.resolutionHorz,f=this.hmdInfo_.resolutionVert,h=a.viewport[0],g=a.viewport[1],r=a.viewport[2],q=a.viewport[3],s=r*e/(q*f),t=1/this.stereoParams_.getDistortionScale(),u=this.tmpMat4_;b.mat4f.makeRect(u,h,g,r,q);d.uniformMatrix4fv(c.uniforms.u_texMatrix,!1,u);d.uniform2f(c.uniforms.u_lensCenter,h+(r+a.distortionCenterOffsetX/2)/2,g+q/2);d.uniform2f(c.uniforms.u_screenCenter,h+r/2,g+q/2);d.uniform2f(c.uniforms.u_scale,r/2*t,q/2*t*s);d.uniform2f(c.uniforms.u_scaleIn,
2/r,2/q/s);d.viewport(h*e,0,r*e,f);a=c.attributes.a_xy;c=c.attributes.a_uv;d.enableVertexAttribArray(a);d.enableVertexAttribArray(c);d.bindBuffer(d.ARRAY_BUFFER,this.quadBuffer_);d.vertexAttribPointer(a,2,d.FLOAT,!1,16,0);d.vertexAttribPointer(c,2,d.FLOAT,!1,16,8);d.drawArrays(d.TRIANGLES,0,6);d.bindBuffer(d.ARRAY_BUFFER,null);d.bindTexture(d.TEXTURE_2D,null)};b.StereoRenderer.PROGRAM_ATTRIBUTE_NAMES_=["a_xy","a_uv"];b.StereoRenderer.PROGRAM_UNIFORM_NAMES_="u_texMatrix u_tex0 u_lensCenter u_screenCenter u_scale u_scaleIn u_hmdWarpParam u_chromAbParam".split(" ");
b.StereoRenderer.PROGRAM_VERTEX_SOURCE_="attribute vec2 a_xy;\nattribute vec2 a_uv;\nvarying vec2 v_uv;\nuniform mat4 u_texMatrix;\nvoid main() {\n  gl_Position = vec4(2.0 * a_xy - 1.0, 0.0, 1.0);\n  v_uv = (u_texMatrix * vec4(a_uv, 0.0, 1.0)).xy;\n}";b.StereoRenderer.STRAIGHT_FRAGMENT_SOURCE_="precision highp float;\nvarying vec2 v_uv;\nuniform sampler2D u_tex0;\nvoid main() {\n  gl_FragColor = texture2D(u_tex0, v_uv);\n}";b.StereoRenderer.WARP_FRAGMENT_SOURCE_="precision highp float;\nvarying vec2 v_uv;\nuniform sampler2D u_tex0;\nuniform vec2 u_lensCenter;\nuniform vec2 u_screenCenter;\nuniform vec2 u_scale;\nuniform vec2 u_scaleIn;\nuniform vec4 u_hmdWarpParam;\nvec2 hmdWarp(vec2 texIn) {\n  vec2 theta = (texIn - u_lensCenter) * u_scaleIn;\n  float rSq = theta.x * theta.x + theta.y * theta.y;\n  vec2 theta1 = theta * (u_hmdWarpParam.x + u_hmdWarpParam.y * rSq + \n      u_hmdWarpParam.z * rSq * rSq + u_hmdWarpParam.w * rSq * rSq * rSq);\n  return u_lensCenter + u_scale * theta1;\n}\nvoid main() {\n  vec2 tc = hmdWarp(v_uv);\n  if (any(notEqual(clamp(tc, u_screenCenter - vec2(0.25, 0.5), \n      u_screenCenter + vec2(0.25, 0.5)) - tc, vec2(0.0, 0.0)))) {\n    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);\n  } else {\n    gl_FragColor = texture2D(u_tex0, tc);\n  }\n}";
b.StereoRenderer.WARP_CHROMEAB_FRAGMENT_SOURCE_="precision highp float;\nvarying vec2 v_uv;\nuniform sampler2D u_tex0;\nuniform vec2 u_lensCenter;\nuniform vec2 u_screenCenter;\nuniform vec2 u_scale;\nuniform vec2 u_scaleIn;\nuniform vec4 u_hmdWarpParam;\nuniform vec4 u_chromAbParam;\nvoid main() {\n  vec2 theta = (v_uv - u_lensCenter) * u_scaleIn; // Scales to [-1, 1]\n  float rSq = theta.x * theta.x + theta.y * theta.y;\n  vec2 theta1 = theta * (u_hmdWarpParam.x + u_hmdWarpParam.y * rSq +\n      u_hmdWarpParam.z * rSq * rSq +\n      u_hmdWarpParam.w * rSq * rSq * rSq);\n  vec2 thetaBlue = theta1 * (u_chromAbParam.z + u_chromAbParam.w * rSq);\n  vec2 tcBlue = u_lensCenter + u_scale * thetaBlue;\n  if (any(notEqual(clamp(tcBlue, u_screenCenter - vec2(0.25, 0.5),\n      u_screenCenter + vec2(0.25, 0.5)) - tcBlue, vec2(0.0, 0.0)))) {\n    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);\n    return;\n  }\n  vec2 tcGreen = u_lensCenter + u_scale * theta1;\n  vec2 thetaRed = theta1 * (u_chromAbParam.x + u_chromAbParam.y * rSq);\n  vec2 tcRed = u_lensCenter + u_scale * thetaRed;\n  gl_FragColor = vec4(\n      texture2D(u_tex0, tcRed).r,\n      texture2D(u_tex0, tcGreen).g,\n      texture2D(u_tex0, tcBlue).b,\n      1);\n}";
f.vr=b})(window);
