name: First Workflow

on:
  push:
    branches: [gh-pages]  # ここも main から gh-pages に変更しました

jobs:
  hello:
    runs-on: ubuntu-latest  # コロンの後にスペース追加

    steps:
      - name: 挨拶
        run: echo 'Hello GitHub Actions! 田中です!'  # インデント修正＆スペース追加

      - name: 現在時刻
        run: date
